id: P000429
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD17435
  title: དམངས་ཁྲིམས་བསླབ་དེབ།
  author: ''
  volumes:
    048347562fb246f6870b9a08e48fcb8e:
      image_group_id: I4PD3053
      title: Volume 1 of dmangs khrims bslab deb/
      volume_number: 1
      total_pages: 722
      base_file: v001.txt
