id: I11D151C5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:36:59+00:00'
last_modified: '2022-06-10T05:33:58.807581+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17435
  title: དམངས་ཁྲིམས་བསླབ་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    10EC:
      image_group_id: I4PD3053
      title: Volume 1 of dmangs khrims bslab deb/
      total_pages: 722
      order: 1
      base_file: 10EC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
